### ISSUE TITLE
Issue with native node modules.

### ISSUE THREAD

**Issue by hadees** [SimulatedGREG/electron-vue#13]
I've been beating my head against the wall to get [webchimera.org](http://www.webchimera.org/) to load.  Specifically the module `WebChimera.js.node` from their [prebuilt](https://github.com/Ivshti/wcjs-prebuilt).  I know it should work because I can get it to load in the `main` process and I've also done it succesffully in `render` with the demo [wcjs-ugly-demo](https://github.com/RSATom/wcjs-ugly-demo) but for some reason adding your awesome template to the mix screws things up.

The main error is this...

```
ERROR in ./app/~/webchimera.js/WebChimera.js.node
         Module parse failed: /Users/gremlin/code/signal/app/node_modules/webchimera.js/WebChimera.js.node Unexpected character '�' (1:0)
         You may need an appropriate loader to handle this file type.
         SyntaxError: Unexpected character '�' (1:0)
             at Parser.pp$4.raise (/Users/gremlin/code/signal/node_modules/acorn/dist/acorn.js:2221:15)
             at Parser.pp$7.getTokenFromCode (/Users/gremlin/code/signal/node_modules/acorn/dist/acorn.js:2756:10)
             at Parser.pp$7.readToken (/Users/gremlin/code/signal/node_modules/acorn/dist/acorn.js:2477:17)
             at Parser.pp$7.nextToken (/Users/gremlin/code/signal/node_modules/acorn/dist/acorn.js:2468:15)
             at Parser.parse (/Users/gremlin/code/signal/node_modules/acorn/dist/acorn.js:515:10)
             at Object.parse (/Users/gremlin/code/signal/node_modules/acorn/dist/acorn.js:3098:39)
             at Parser.parse (/Users/gremlin/code/signal/node_modules/webpack/lib/Parser.js:902:15)
             at DependenciesBlock.<anonymous> (/Users/gremlin/code/signal/node_modules/webpack/lib/NormalModule.js:104:16)
             at DependenciesBlock.onModuleBuild (/Users/gremlin/code/signal/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
             at nextLoader (/Users/gremlin/code/signal/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
             at /Users/gremlin/code/signal/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
             at Storage.finished (/Users/gremlin/code/signal/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
             at /Users/gremlin/code/signal/node_modules/graceful-fs/graceful-fs.js:78:16
             at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
          @ ./app/~/webchimera.js/index.js 1:17-48
```

But I'm pretty sure webpack shouldn't be reading binary files like that.

To fix it I've tried so many different things, like `externals` but nothing seems to work.
```
{ 
  externals: { 'webchimera.js': "commonjs2 webchimera.js" }
}
```

that does let the page load but it'll never find `webchimera.js` if I tried to require it.

I'm on the verge of dropping `webpack` for `gulp`

**Comment by SimulatedGREG** [comment]
@hadees 

> You may need an appropriate loader to handle this file type.

It would seem you are trying import the file `WebChimera.js.node` which has the extension of `.node`. By default electron-vue doesn't know how to handle the `.node` extension. You can edit `webpack.config.js` to support this by changing [L31](https://github.com/SimulatedGREG/electron-vue/blob/master/template/webpack.config.js#L31) to...

Hope this helps 🙂.
```js
test: /\.(js|node)$/,
```

**Comment by hadees** [comment]
@SimulatedGREG thanks for the fast response!  No dice on the fix, still getting that error.  Here are my [full logs](https://gist.github.com/hadees/de6c39729bb3b49cd5dd702583085036) if that helps.

**Comment by SimulatedGREG** [comment]
@hadees do you have a repo I could look at... 👀

**Comment by hadees** [comment]
@SimulatedGREG [here is a repo I just pushed up](https://github.com/hadees/example).  If you want to run it you'll need to make sure you have electron at version `1.3.1` and have a prebuild installed in the `app/node_modules`.  I have the OSX one in the repo.

Thanks for the help

**Comment by SimulatedGREG** [comment]
I've been trying to get the prebuilt library installed from npm, but it seem the prebuilt doesn't exist for electron `v1.3.1` on the registry (and then sometimes it does????). Went ahead and extracted the contents of the library you provided and put the folder into `app/node_modules`.

It's simple to import/require the prebuilt-binary in the app, but the problem that happens is that webpack doesn't know it shouldn't be bundling a binary file. To get around this, you would need to require the module within your `app/src/main.ejs` and make the module available to global scope. The 2 major side-effects of doing this is that when you build your app for production `node_modules` are not included, therefore the prebuilt-binary would need to be added back manually after building. The other problem is that `require` doesn't work like it should in development (webpack does some sort of hijacking that I can't figure out how to adjust), meaning in order to actually test anything related to the module you would have to build your app every time (which is very counterintuitive).

### **a few hours later...**

I found a loader that supposedly supports bundling .node binaries. Went ahead and did `npm install https://github.com/kevzettler/node-loader` and was able to require it by doing...

**App.vue**
```html
<script>
  import store from 'src/vuex/store'
  window.wcjs = require('node!webchimera.js/WebChimera.js.node')

  export default {
    ready () {
      console.log(window.wcjs)
    },
    store
  }
</script>
```
I was able to get the above code working fine and was able to look at the module in the dev tools. Unfortunately, it would seem as soon as the library is used (i.e. `window.wcjs.createPlayer()`) electron just freezes indefinitely. Because of this, I'm unable to determine if the `node-loader` is creating an issue or if the prebuilt binary is unstable with electron `v1.3.1`.

In the end, native node modules are still rather difficult to work with reliably (speaking from friends/personal experience). I'm sorry I wasn't able to provide a decent solution for you. I've had similar cases in the past with native node modules and have always had to do something hacky in the end. Webpack was meant for mainly handling JS modules and has been *somewhat* adapted to go further towards electron specifics.

You did mention that you were able to get this module working inside the main process, so you might be able to expose the module to the global scope and share it to the renderer process. This might be the best case scenario (if it works properly). Here's the docs for that... [https://github.com/electron/electron/blob/master/docs/api/remote.md#remotegetglobalname](https://github.com/electron/electron/blob/master/docs/api/remote.md#remotegetglobalname).

I'm going to close the as it doesn't pertain to an internal problem with electron-vue itself. Best of luck to you. 😕

**Comment by hadees** [comment]
The thing about webpack that I still don't really understand is what it must be doing to require to end up with different results.

Anyway I do like your file format, could you perhaps offer some advice on how to it with `gulp`?  I do a lot of coffeescript day to day but not a whole lot of node.  Right now I was figuring copying everything over to `app/dist` and having electron load that file.  I'm not sure what the build would be but I figure it would end up similar to yours.
