### ISSUE TITLE
Going directly to a route throws a 404

### ISSUE THREAD

**Issue by matiastucci** [SimulatedGREG/electron-vue#139]
### Found an issue or bug? Tell me all about!

I'm implementing a Google login. The problem is that after I enter my credentials Google redirects me to `/foo` and that is not working well. I'm seeing a `Cannot GET /foo` message in the app. I found in the `vue-router` (I'm using HTML5 history mode) [documentation](https://router.vuejs.org/en/essentials/history-mode.html) some server configurations, but I'm not sure how to do that in this case. Any Ideas?

##### How can I reproduce this problem?
From devtools' console do something like `window.location = '/foo'`. `foo` being a route you have declared.

##### Tell me about your development environment.
  * Node version: `process.version === "v6.5.0"`
  * Electron version: `process.versions.electron === "1.4.15"`
  * Operating System: OS X

**Comment by SimulatedGREG** [comment]
The default nature of `vue-router` uses hash mode where `/foo` would actually be `/#/foo`. But in your case, trying to login in with Google, I don't think will work as intended unless you spawn another BrowserWindow. I say this because in production, the app is served of the `file://` protocol. You might want to look into https://github.com/parro-it/electron-google-oauth or something similar.

**Comment by matiastucci** [comment]
yeah, I was using HTML5 history mode. Even if I use hash mode there is no way to do the OAuth just like in a normal webpage?

**Comment by SimulatedGREG** [comment]
Not really, unfortunately. That's just electron in general, and doesn't specifically apply to `electron-vue` alone. And as I mention within the docs, please refrain from using HTML5 history mode, as it won't work in production on the `file://` protocol.

**Comment by matiastucci** [comment]
Sigh, I guess I'll try `electron-google-oauth`. Thanks for the answer man. I love `electron-vue` ❤️
