### ISSUE TITLE
build app is blank

### ISSUE THREAD

**Issue by hackboy** [SimulatedGREG/electron-vue#143]
##### Describe the issue / bug.
\#

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

#### *If you are looking to suggest an enhancement or feature, then feel free to remove everything above.*

when i use 'npm run dev',the app is ok,but after i npm run build,execute the app only has a blank page.
I find issue in the issues,somebody say the issue is vue-router should set to hash,i try it,but that not works,
can someone tell me the reason,thanks

**Comment by emanuelgsouza** [comment]
Hi, @hackboy. Could you give us more context of your problem? An print of page, for example. The print of terminal, too.

**Comment by royJang** [comment]
same problem, when i execute `npm run build:darwin` then open the app.
the app is blank :(

**Comment by royJang** [comment]
There may be some packages use `debug`
but `Uncaught Error: Cannot find module 'debug'`
what should i do ?

**Comment by royJang** [comment]
@hackboy  i used electron-builder  instead of electron-packager, and then just fine!

**Comment by hackboy** [comment]
@emanuelgsouza I have resolved the problem,the reason is that the npm pack renender failed

**Comment by mmorainville** [comment]
Hi @hackboy,

I've the exact same problem, the app is blank and I have the error `Cannot find module 'debug'`.
Could you tell me please how you made the npm pack not failed?

Regards,
M.

**Comment by welintonti** [comment]
Hi @hackboy,

I also have the same problem, but I believe it has more to do with the structure of my project than with the webpack builder process. One thing I did to get around the problem was to pass the full path of the `dist` directory on line 9 of the` app / src / main / index.js` file. Only then I was able to generate the build of my application. I'm still checking, because it only works that way. If I can find a definitive solution, I'll post the solution here. One important note, and I think it is related to my problem, is that I do the build in 32-bit Windows (arggg).

**Comment by dreamfliper** [comment]
Same problem here, but I fix it by change `asar: true` to `false` in config.js. This might be caused by non-pure-js package. I use an OpenCC package which is written in C source with nodejs api, and I need to use electron-rebuilder to make `npm run dev` work.

**Comment by SimulatedGREG** [comment]
If you guys are trying to use native node modules (those written in C), you will most likely have better success with `electron-builder` as its build process will automatically rebuild those modules against the electron environment. When using `electron-packager` you will have to manually use `electron-rebuild` to make sure things are built correctly. This would also explain why these modules only work in development. I'll be adding some documentation about this issue. Please feel free to comment back if you guys have any other questions.

**Comment by disarticulate** [comment]
Just wanted to provide a solution I fixed as described in the comments above, I did the following:
```
vue init simulatedgreg/electron-vue fixed-project-dir
? Application Name fixed-project-dir
? Project description An electron-vue project
? Select which Vue plugins to install vue-electron, vue-resource, vue-router
? Use linting with ESLint? No
? Setup unit testing with Karma + Mocha? No
? Setup end-to-end testing with Spectron + Mocha? No
? What build tool would you like to use? builder
```
Then copied my current app to the new app directory. As stated above, it looks like package can't manage whatever I did, which is I assume dependencies. Although `builder` gives me this line:
`No native production dependencies`

So I'm unsure what the root cause is.

**Comment by shenliuming** [comment]
hello,so the problem is work out ?
