### ISSUE TITLE
New added node modules are not properly packaged

### ISSUE THREAD

**Issue by wizcas** [SimulatedGREG/electron-vue#154]
##### Describe the issue / bug.
\#
The node modules I installed besides the default ones are not properly packaged.
I extracted the app.asar file and there are `.x.x.x@xxxx` folders in `node_modules`. Folders that should contain distributing js files are empty

**WHICH IS THE REASON WHY JQUERY CANNOT BE LOADED, I GUESS. I'VE BEEN STRUGGLING WITH THIS SHITE FOR 2 DAYS. PLEASE HELP ME**

##### How can I reproduce this problem?
\#
here's my `package.json` in app

```
{
  "name": "test-vueee",
  "version": "0.0.0",
  "description": "test-vueee",
  "main": "./dist/main.js",
  "dependencies": {
    "bootstrap": "^3.3.7",    <-----new
    "jquery": "^3.1.1",          <-----new
    "js-md5": "^0.4.2",         <-----new
    "moment": "^2.17.1",     <-----new
    "numeral": "^2.0.4",       <-----new
    "vue": "^2.1.10",
    "vue-electron": "^1.0.6",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.1.2",
    "vuex": "^2.1.1"
  },
  "devDependencies": {},
  "author": "Wizcas <wizcas@qq.com>"
}
```

##### If visual, provide a screenshot.
\#
![image](https://cloud.githubusercontent.com/assets/2867434/23911682/7fc76cb0-0918-11e7-9a0f-9f7255683416.png)

##### Tell me about your development environment.
  * Node version: 7.4.0
  * NPM version: 4.3.0
  * vue-cli version: (if necessary) 2.8.0
  * Operating System: Windows 10

**Comment by chovy** [comment]
Are these peer dependencies?

**Comment by wizcas** [comment]
@chovy I'm not quite familiar with npm.They all rely on jquery, and I guess they are peer dependencies. just did a quick reading about peer dependencies. do I need to config them respectively?

**Comment by wizcas** [comment]
And I just tried building my project on Mac. Seems everything's fine. The `node_modules` in the built package is clean and doesn't have the @ things:
![image](https://cloud.githubusercontent.com/assets/2867434/23929493/9c3f1444-0961-11e7-8683-c3c4c8a22af1.png)

**Comment by chovy** [comment]
jQuery and bootstrap are usually declared as peerDependencies for modules that rely on them. The reason is they don't have to be distributed with the module because its likely some upstream package has already required them.

For example if I build an app I would require bootstrap and jQuery, no need for a bootstrap module I'm using to also be packaged with bootstrap core so its declared as a "peerDependency". Usually you can just resolve that by making them dependencies in your base app or just installing them directly.

**Comment by wizcas** [comment]
@chovy Thanks for the explanation. In my case, however, I've declared bootstrap and jQuery explicitly in my `app/package.json`, and there is not any peer dependency anywhere in my project. If I'm thinking right about what you sugguest, aren't they supposed to be distrubuted with my app?

**Comment by wizcas** [comment]
I think I just solved this issue...unexpectedly
For unknown reason the installed node modules are all symbol links:
![image](https://cloud.githubusercontent.com/assets/2867434/23954956/825fd6f4-09d3-11e7-9987-04f2b0fbfd2a.png)
I justed deleted the app/node_modules folder and reinstalled, making sure none of the module folders is symlink. Everything seems fine now

Wierd

**Comment by SimulatedGREG** [comment]
Sounds this was more of an NPM issue. This is party why [`yarn`](https://yarnpkg.org) has gotten popular because these type of issues are handled much better. I'm probably going to update the docs soon and officially recommend using `yarn`, as it not only performs better but its actually better for production build file sizes.

Feel free to comment back if anybody has more questions.

**Comment by wizcas** [comment]
Cool. Never tried yarn before. gonna give it a go ;)
