### ISSUE TITLE
how to debug main process in vscode for current version? #83 answser can not work well.

### ISSUE THREAD

**Issue by shmilyoo** [SimulatedGREG/electron-vue#180]
I use the launch.json as #83 

	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/app/electron.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
                        // this points to the electron task runner
			"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "production"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"sourceMaps": false,
			"outDir": null,
			"localRoot": "${workspaceRoot}",
			"remoteRoot": null
		}
	]

when set "program": "${workspaceRoot}/app/src/main/index.dev.js", start debug ,and the page is empty.
when set "program": "${workspaceRoot}/app/src/main/index.js", an error occurred, on index.js :3 
import { app, BrowserWindow } from 'electron' 
unexpected token import ， it seems the debug can not support import syntax

**Comment by SimulatedGREG** [comment]
@shmilyoo 

When using `index.dev.js` you are getting a blank window because `webpack-dev-server` is not serving your app in development mode. You can manually fire that with the command below, and then launch from VSCode.
```bash
webpack-dev-server --hot --colors --config webpack.renderer.config.js --port 9080 --content-base app/dist
```

#83 describes how you can debug with a production build and that would need to point to `app/dist/main.js` and a successful `npm run pack`. Also if you are on Windows, then you'll need to update your `runtimeExecutable` to point at `electron.cmd`.

**Comment by shmilyoo** [comment]
it worked! But it is still difficult to debug . Expect the next milestone. Thanks!!!
