### ISSUE TITLE
Cannot find jQuery when import bootstrap

### ISSUE THREAD

**Issue by inseptember** [SimulatedGREG/electron-vue#192]
##### Describe the issue / bug.
\#cannot find jQuery, after i set nodeIntegration: false, then report cannot find require function

##### How can I reproduce this problem?
\#import jquery and bootstrap in main.js

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:6.10.2
  * NPM version:3.10.10
  * vue-cli version: (if necessary)2.8.1
  * Operating System:windows 10

**Comment by SimulatedGREG** [comment]
Okay so if you want to use regular jquery and bootstrap, here's what needs to be done...

Add ProvidePlugin in **webpack.renderer.config.js** around line 90
```js
new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery: 'jquery'
})
```
and in **main.js**...
```js
window.jQuery = window.$ = require('jquery/dist/jquery.min')
import 'bootstrap/dist/js/bootstrap.min'
import 'bootstrap/dist/css/bootstrap.min.css'
```

Now I highly discourage using jQuery and Vue in the same environment because you are now using two frameworks for the same app. This not only bloats your app size, but it can also very easily lead to anti-patterns between Vue and jQuery.  As an alternative you can look into something like [`vue-strap`](http://yuche.github.io/vue-strap/) which takes bootstrap's JS functionalities and converts them to Vue instead of jQuery. This way to have better control over your data in the long run.

**Comment by felipetesc** [comment]
Even though, this 'post' is closed, I wanted to ask what alternative to jquery I can use, and if any of you can share a possible suggestion. I'll hard code all components, but I really want a lib for dom manipulation. By the way, I'm not asking for something I can google, but what lib have you used in that way (dom manipulation) with electron-vue. TY!
