### ISSUE TITLE
[Bug] Refresh needed to trigger methods

### ISSUE THREAD

**Issue by GweltazCalori** [SimulatedGREG/electron-vue#210]
##### Describe the issue / bug.
Hi, so my problem is that when I run `npm run dev` not all the methods inside the mounted method are called. In my case it specifically the firebase `db.ref().on()` method. It's the same thing no matter the component (in my case it was` App.vue`). So the only way to make it working is once I ran `npm run dev `press `F5 `to refresh.

Note that I did that on a **non electron-vue** project using vue-cli and webpack and I never had any problems.

###### ./app/src/renderer/firebaseconfig.js
```
import Firebase from 'firebase'
var config = {
	apiKey: "myapikey",
    authDomain: "mydomain",
    databaseURL: "myurl",
    storageBucket: "mystoragebucket",
    messagingSenderId: "mymessagingSenderId"
};

var firebaseApp = Firebase.initializeApp(config);
var db = firebaseApp.database();

export {db};
``` 

###### ./app/src/renderer/App.vue

```
import {db} from './firebaseconfig.js'
export default {
    mounted()
    {
      console.log(db) // This is working (I can see the db object)
      db.ref('myid/lang').on('value', (snapshot) =>{ //this is never called
            console.log("called")        
        });
    }
  }
```

##### To reproduce the problem. 

 * Just create a new electron-vue project using the normal settings (vue-resource, vuex, vuerouter).
 * Then just run `npm install firebase --save` inside the `./app` directory.

##### My environnement
  * Node version: v6.7.0
  * NPM version: 3.10.3
  * vue-cli version: 2.7.0
  * Operating System: Windows

**Comment by SimulatedGREG** [comment]
@GweltazCalori 

This is not an issue with electron-vue. `db.ref('myid/lang').on('value', <Function>)` creates an event listener and will run `console.log('called')` on every new `value`. This works the first time (or on page refresh with `F5`) because the data is loaded in for the first time therefore emitting a `value` event. It doesn't work on a hot-reload because the value at `myid/lang` still hasn't changed, so the `value` event will not fire. This is expected behavior and should also happen on the official `vuejs-templates/webpack` scaffold as well.

You also stated that `console.log(db)` is "working" meaning that both functions will run. JavaScript isn't going to randomly stop in the middle of a function and "not [run] all the methods", and no `webpack` config is going to do that either.

I would highly recommend not to handling data within App.vue and would recommend moving/exporting from another file or use `vuex` to hydrate your components with data.

**Comment by GweltazCalori** [comment]
Thanks for the reply. Actually it's working in our webpack project so this is weird. The only thing I don't understand is why moving it to vuex will change something. Also the same thing happen if I move to another component. We used Vuex in the project but not for this specific part.

**Comment by gweltaz-calori** [comment]
You said that

> This works the first time 

But in my case it's the opposite. It's not working the **first time** but working on **reload** or on modification of any files.

**Comment by GweltazCalori** [comment]
You said that

> This works the first time 

But in my case it's the opposite. It's not working the **first time** but working on **reload** or on modification of any files.

**Comment by EmadAdly** [comment]
I've the same issue
