### ISSUE TITLE
The path of picture

### ISSUE THREAD

**Issue by lianshengxing** [SimulatedGREG/electron-vue#224]
`const iconPath =  path.join(__dirname, '/logo/logo.png')
 tray = new Tray(iconPath)`

it`s not work after i package the project

**Comment by SimulatedGREG** [comment]
`webpack` doesn't know to handle that image file. The image needs to be placed in the static assets folder and referenced accordingly due to the `__dirname` differences. 

https://simulatedgreg.gitbooks.io/electron-vue/content/en/renderer-process.html#using-static-assets
https://simulatedgreg.gitbooks.io/electron-vue/content/en/main-process.html#on-the-subject-of-using-dirname--filename
