### ISSUE TITLE
[HELP] Confused about how to use component assets

### ISSUE THREAD

**Issue by voveson** [SimulatedGREG/electron-vue#227]
First of all, serious kudos for your work on this project! 

##### Describe the issue / bug.
I'm trying to follow the instructions [here](https://simulatedgreg.gitbooks.io/electron-vue/content/en/renderer-process.html#vue-components), specifically where it says to create a directory with the same name as your Vue component, then a subdirectory called `assets`, and include the component's assets there.  I'm just not sure where to go from there -- how do I access the asset from the Vue component?

Specifically, I am trying to customize the `Notification` sound using an `.mp3` asset.  If there's a better way to accomplish that, please point me in the right direction!

##### Tell me about your development environment.
  * Node version:  v6.8.1
  * NPM version:  v3.10.8
  * Operating System: Mac osX El Capitan

**Comment by SimulatedGREG** [comment]
@voveson 

Since a `*.mp3` isn't handled by `webpack` and `vue-loader` isn't parsing assets in your JS, this won't be possible in development or production. Because the asset isn't being handled, it will never reach the final production build. The sound file would need to be treated as a static asset and referenced accordingly with a path to the asset. The current state of electron-vue doesn't provide much help for getting a path to your assets. The next milestone release in the `dev` branch (coming rather soon, #171) has made some major adjustments to help support these type of situations. Here is a link to the documentation that will launch with the next milestone release (https://simulatedgreg.gitbooks.io/electron-vue/content/v/9772e38a3e73c5610ba845b2d07103d1b2a7a29d/en/using-static-assets.html#use-case-within-js-with-fspath-and-static).

**Comment by lianshengxing** [comment]
i meet the err that '__static is undefined'

**Comment by SimulatedGREG** [comment]
@lianshengxing 

This feature isn't released in the `master` branch yet and currently only available in `dev`. See #171 for more info.

**Comment by lianshengxing** [comment]
@SimulatedGREG 
could i follow this 'https://github.com/SimulatedGREG/electron-vue/commit/131b8416990e5a38980e95a682e67f284f6614ce' to fix my err?

**Comment by SimulatedGREG** [comment]
That's only part of the solution. I would recommend scaffolding a new app from `dev` and migrating your `src` files over to the new scaffold.

**Comment by lianshengxing** [comment]
@SimulatedGREG 
there is only a master branch in my project,no dev branch, i build my project with 'vue init simulatedgreg/electron-vue my-project'

**Comment by SimulatedGREG** [comment]
As explained in #171, you can scaffold the `dev` branch using...
```bash
vue init simulatedgreg/electron-vue#dev my-project
```

**Comment by voveson** [comment]
@SimulatedGREG Thanks for the info -- I look forward to the future release!

Another question:  Would moving my `Notification` code to the main process make it easier to get a a path to my `*.mp3` asset?  I'm sure I could use `ipc` to trigger the notification if that is the case.

This might be a silly question -- forgive me, I'm a total novice when it comes to Electron!  Thanks again for your help!

**Comment by SimulatedGREG** [comment]
Getting path to the static assets would still be an issue. The main problem to understand that your `src` directory does not exist in production, there for all those files will never be available.

**Comment by voveson** [comment]
Thanks for your help, Greg!
