### ISSUE TITLE
$router.push and $router.route.go don't work

### ISSUE THREAD

**Issue by rafa-acioly** [SimulatedGREG/electron-vue#232]
I'm trying to create a redirect in a login component and when using `this.$router.push('somewhereelse')` or  `this.$router.route.go('somewherelse')` the 2 functions return "undefined".

**Comment by SimulatedGREG** [comment]
@rafa-acioly 

The `$router.push` API by default does not return anything, so it's expected to see 'return "undefined"'. But it sounds like you are running into a different issue. Maybe you didn't register that named route correctly? I'm going to close this since it is not a direct issue with electron-vue, but feel free to comment back any further details such as some of the code your are using or even a link to a project repo and I can take a look.

**Comment by dqj** [comment]
I've the same issue.
