### ISSUE TITLE
adding "artifactName" field to package.json doesn't change the output file

### ISSUE THREAD

**Issue by syonip** [SimulatedGREG/electron-vue#266]
Hello,
I've added "artifactName" field to package.json, but the output file stays the same.
There are two package.json files, one in the root dir, and one inside /app.

The root level package.json:

```
"build": {
    "artifactName": "${name}-${version}-${os}.${ext}",
    "productName": "VueElectron",
    "appId": "com.pepo.vue-electron",
    "category": "public.app-category.tools",
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "files": [
      "dist/",
      "node_modules/",
      "package.json"
    ],
    "mac": {
      "icon": "app/icons/icon.icns"
    },
    "win": {
      "icon": "app/icons/icon.ico"
    },
    "linux": {
      "target": [
        "AppImage"
      ]
    }
  },
```

running "npm run build" produces "VueElectron Setup 0.0.0.exe" (disregarding the artifactName).
I've also noticed that changing the "version" in the main package.json doesn't affect the output file, but changing the version in /app/package.json DOES change the name of the output file.

Thanks in advance!

#########
  * Node version: 6.11.0
  * NPM version: 3.10.10
  * vue-cli version: (if necessary)
  * Operating System: Windows

**Comment by SimulatedGREG** [comment]
@syonip 

 The `version` will come from `app/package.json` because the use of the 2 `package.json` structure. You also typically want to change the version for every build you make, as I'm not sure if `electron-builer` will overwrite previous builds. I'm not entirely sure what happened based on what you described, but this is definitely not an issue with electron-vue. Hope this helps.
