### ISSUE TITLE
How to log console.log to file from renderer?

### ISSUE THREAD

**Issue by alexcroox** [SimulatedGREG/electron-vue#274]
I'm using the latest electron-vue (minimize milestone).

I'm trying to get all console.log() from both main and renderer processes into a log file. I'm using [electron-log](https://github.com/megahertz/electron-log) and adding `console.log = log.info` to both `main/index.js` and `renderer/main.js`.

In development this works great, the dev console and `log.log` file show logs from both main and renderer. 

However when I build, using electron builder, I only ever get the main process console.logs in both dev console and log file.

Would there be anything in this boilerplate causing that?

**Comment by SimulatedGREG** [comment]
Not entirely sure where the issue could be coming from, but during the build process, `babili-webpack-plugin` is set to remove all console statements during production. This sort of makes sense, but not really because you said that you are getting logs from at least the `main` process.

Here are two sections you can try to comment out and then re-run a build...
https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.renderer.config.js#L156
https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.main.config.js#L79

If commenting those out works, then it's safe to keep them off. If that doesn't work, you may want to try setting up the logger in the `main` process and share it to the `renderer` process with [`remote.getGlobal`](https://electron.atom.io/docs/api/remote/#remotegetglobalname), this way you can be confident in using the same `electron-log` instance for both processes.

**Comment by alexcroox** [comment]
That did the trick thanks!
