### ISSUE TITLE
Support for electron remote?

### ISSUE THREAD

**Issue by alexcroox** [SimulatedGREG/electron-vue#289]
Not sure if this would be out of scope for this project but I'm really struggling with heavy computational tasks / lots of API calls locking up my renderer UI. I can't move them to main as that could lock up the window, and [electron-remote](https://www.npmjs.com/package/electron-remote) seems to aid with spawning new threads and handling communication automatically for you. I can't for the life of me get it working with this boiler plate however, I'm pretty sure it's because of the webpack `require.resolve` conflicts. 

Are there any other solutions to this problem?

**Comment by SimulatedGREG** [comment]
If the issue is related to `require.resolve` issues, then in short it will probably never work as expected within a `webpack` environment. I'm out of town for the foreseeable future and won't have much time to experiment with this at the moment. Might be worth writing an individual api for this setup. It sounds interesting to solve, but just don't have the time at the moment. 

Going to close as this isn't a direct issue with electron-vue, but will keep this in mind.
