### ISSUE TITLE
Can not pack flash plugin

### ISSUE THREAD

**Issue by wenpengfei** [SimulatedGREG/electron-vue#313]
I use electron-builder(npm run build) pack app and put flash plugin in __static folder, It is OK in dev environment. But in packed app It shows can not load plugin.

**Comment by SimulatedGREG** [comment]
@wenpengfei 

I personally haven't used the flash plugin myself. Do you have a project repo I could take a look at?

**Comment by wenpengfei** [comment]
@SimulatedGREG 
Sorry, it's too late to replay. The repo is https://github.com/wenpengfei/electron-vue-flash

**Comment by wenpengfei** [comment]
Any results? :persevere: :persevere: :persevere:

**Comment by SimulatedGREG** [comment]
@wenpengfei 

Sorry for the late reply. It has been a combination of being out of town, catching up on things, and preparing to leave town again, haha.

Anyways, in production since the `static/` folder is packed in the `asar` archive, `electron` can't get a OS level path to the attach the flash plugin. A super quick fix to this problem, would be to set `asar: false` in the `build` section of your `package.json`.

**Comment by wenpengfei** [comment]
thanks~

**Comment by Insua** [comment]
@SimulatedGREG I use electron packager and I change asar: false in build.config.js and It work fine,but I want to only unpack flash plugin however unpack all files,How to solve it?
