### ISSUE TITLE
Unable to access remote.app.getPath('userData') in dev mode

### ISSUE THREAD

**Issue by benlipp** [SimulatedGREG/electron-vue#334]
##### Describe the issue / bug.
Any attempt to access the app's userData in development mode results in a 404 error, because the dev server does not host the userData file system. I've looked at issue #165 and issue #216, but none of these actually solve the problem that userData is unavailable in dev mode. I was able to get it working by prepending `file://` and disabling `webSecurity` on my browser window, but I obviously don't want that for my final build.

##### How can I reproduce this problem?
Access a file by using `this.$electron.remote.app.getPath('userData')` in a Vue component.

##### Tell me about your development environment.
  * Node version: v7.10.1
  * NPM version: 5.3.0
  * Operating System: Ubuntu 16.04

**Comment by SimulatedGREG** [comment]
@benlipp sorry for the late reply.

This is expected behavior within `electron` or more specifically within the browser-land restrictions. Loading local resources is blocked for the same reasons Google Chrome, Firefox, etc can't load local resources. Unless the browser is given explicit access to a particular file, such as through a file upload flow, you really can't do this. 

One alternative, aside from disabling `webSecurity`, is to load the assets into memory and consume it from there, but this approach may only work for certain asset types. This also assume you know the file you want to access is available.

**Example**
I have a image assets I want to load into a `<img>` tag. We can use `base64` to achieve this.

```js
import { join, extname } from 'path'
import { readFileSync } from 'fs'

/* ... */
mounted () {
  let imagePath = join(this.$electron.remote.app.getPath('userData'), '/myImage.png')
  let base64Image = readFileSync(imagePath, 'base64')
  let extensionName = extname(imagePath)
  this.finalImg = `data:image/${extensionName.split('.').pop()};base64,${base64Image}`
}
/* ... */
``` 
The result of `this.finalImg` can then be applied with `<img :src="finalImg">`. Please know this is a pretty hacking way to go around this and this will be unperformant with repeated usage or large image files as assets will be loaded into memory.
