### ISSUE TITLE
app.getVersion() getting electron lib version and don't updating 

### ISSUE THREAD

**Issue by CristopherYusuke** [SimulatedGREG/electron-vue#375]
Hello guys , i'm using electron-updater for auto update my app  and it's don't work very well , in the console shows 
![image](https://user-images.githubusercontent.com/4607332/29784205-92765fd8-8bf9-11e7-9914-849e426cbc54.png)

Although my application is in version 0.0.1 in `package.json`

![image](https://user-images.githubusercontent.com/4607332/29784636-235cdbb6-8bfb-11e7-8e91-85fbcb40992a.png)

why this happen ? 

I think  de app.getVersion is getting electron lib version , have some configuration to set in electron-updater or in the electron-core lib ? 

  * Node version:8.1.3
  * NPM version:5.0.3
  * Operating System: win10 x64

**Comment by emjimadhu** [comment]
I am not sure whether this will be helpful in your particular case. But i tried getVersion in my app to show it in About App dialog. I got the same release number. So i figured it was electron's version. So in development mode, it fetches electrons version instead of app's version which is in pacakage.json. But in production build it works perfectly. 

I don't know anything about auto update feature yet. but if you are running in development environment, try production build instead.

**Comment by CristopherYusuke** [comment]
Thanks man , it's work perfectly now. But it is a pity that don't work in the development environment because it would help me a lot to check methods.
But I can move on now , thank you very much

**Comment by SimulatedGREG** [comment]
@CristopherYusuke 

The following documentation explains how the app version is attained, but doesn't necessarily mention the differences during development like @emjimadhu mentions.

>  The version of the loaded application.

It's important to remember that during development you are using a prebuilt binary of electron, and **not** a final production build that your would normally expect. Since the prebuilt version lives in a separate scope of your projects `package.json`, it will then fallback to getting the `electron` version, or the "loaded application".

https://electron.atom.io/docs/api/app/#appgetversion

**Comment by danmo** [comment]
It's a known "issue". I'm using the following to grab the app version 
`const appVersion = require('./package.json').version;`

**Comment by liederivative** [comment]
@SimulatedGREG  Actually you can test updates in development, you just need to mock  the app.getVersion function before importing the 'electron-updater' package. Something like: 

```
import {version} from './package.json';
app.getVersion = ()=> version;
const { autoUpdater } = require("electron-updater");
```
