### ISSUE TITLE
it is blank screen after run it by build

### ISSUE THREAD

**Issue by Chyroc** [SimulatedGREG/electron-vue#398]
##### Describe the issue / bug.
if i run it by `npm run dev`, it is ok

if i build it with `npm build` and run it, it is not ok.(mac and windows have the same error -- blank screen)

##### How can I reproduce this problem?
yes,you can do something below:

1. vue init simulatedgreg/electron-vue my_eletron_vue

and my config is 
```
? Application Name my_eletron_vue
? Project description An electron-vue project
? Select which Vue plugins to install vue-electron, vue-router
? Use linting with ESLint? No
? Setup unit testing with Karma + Mocha? No
? Setup end-to-end testing with Spectron + Mocha? No
? What build tool would you like to use? packager
? author Chyroc <chen_yunpeng@foxmail.com>
```
2. cd my_eletron_vue
3. yarn
4. `npm run dev`, it is ok
5. `npm build` or `npm run build:darwin`,it is blank

##### If visual, provide a screenshot.
![image](https://user-images.githubusercontent.com/15604894/30526951-7d8fe212-9c55-11e7-89d5-5765d3956dc6.png)

##### Tell me about your development environment.
  * Node version: v8.0.0
  * NPM version: 5.0.4
  * vue-cli version: (if necessary) 2.8.2
  * Operating System: mac

**Comment by Chyroc** [comment]
if you can give some suggestion, thank you very much.

**Comment by SimulatedGREG** [comment]
@Chyroc 

Sorry for the trouble you are running into. The use of `electron-packager` is unfortunately very buggy right now, due to horrible `npm` bugs. I would highly suggest trying to use `electron-builder` as many of the issues are handled much better.

If you really need `electron-packager`, then I would suggest trying to use `npm@5.2.0` or maybe settings the package manager to use `yarn`. Hope this helps.

Related: #348
