### ISSUE TITLE
Webpack's DefinePlugin is not replacing anything 

### ISSUE THREAD

**Issue by gordonshieh94** [SimulatedGREG/electron-vue#411]
##### Describe the issue / bug.
This might be more of a webpack issue than the boilerplate doing something incorrectly. 
The resulting output of index.ejs from a build do not replace the string `process.env.NODE_ENV`.

##### How can I reproduce this problem?
`npm run build:web` or `npm run pack:renderer`
Can be reproduced from a fresh init of the boilerplate. To match my existing project, I unselected vue-router during setup.

##### Tell me about your development environment.
  * Node version: 7.10.0
  * NPM version: 4.2.0
  * Operating System: macOS 10.12.6

**Comment by SimulatedGREG** [comment]
Since `html-webpack-plugin` creates the `index.html` file separately, the `DefinePlugin` will not be able to inject any variables. If you really need to inject any variables into your `index.ejs`, then you can pass them in [here](https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.renderer.config.js#L115) access them via EJS templating. Notice that the `nodeModules` variable is passed in using this technique.
