### ISSUE TITLE
Might be a typo in webpack configs.

### ISSUE THREAD

**Issue by utkukaratas** [SimulatedGREG/electron-vue#414]
This might be a wrong alarm (sorry, in that case) but I think there is a typo in webpack configs (both renderer and web.)

Here is the line that configures sourcemaps. Note the pound "#" char.

>  devtool: '#cheap-module-eval-source-map'

As the webpack documentation does not mention anything about that on the 'devtool' field, I think that might be a typo. Just FYI. 

webpack docs: https://webpack.js.org/configuration/devtool/

**Comment by SimulatedGREG** [comment]
There was a time where the `#` was used, but it doesn't seem that is the case anymore. Since `webpack` isn't throwing type errors, then this must be backwards compatible and not breaking anything. Going to ignore since `electron-webpack` migration is in the works and this will no longer be a concern. Thanks for the feedback @utkukaratas.
