### ISSUE TITLE
import 'font-spider' module error？

### ISSUE THREAD

**Issue by Hades-li** [SimulatedGREG/electron-vue#434]
require or import 'font-spider' , run dev is failed。
but，import it in electron-quick-start, is success
<img width="1614" alt="wx20171022-170110 2x" src="https://user-images.githubusercontent.com/12124478/31860387-9f19a380-b74b-11e7-8123-f95c9088097d.png">

font-spider is [https://github.com/aui/font-spider](https://github.com/aui/font-spider)

##### Tell me about your development environment.
  * Node version: 8.6
  * NPM version: 5.3
  * vue-cli version: 2.9.1
  * Operating System: Macos 10.12.6

**Comment by SimulatedGREG** [comment]
I don't believe `font-spider` was built to snoop through JS applications or parse through `webpack` bundles. I'm not sure if this is possible to put together. `font-spider` looks to focus solely on static websites, Vue.js doesn't really fit into that category. 

Also compressions is nice for fonts, but do remember that it isn't as needed for electron applications since your users will already have to download a full-blown application.
