### ISSUE TITLE
Devtron lint check "Using latest Electron version" fails

### ISSUE THREAD

**Issue by Luminess** [SimulatedGREG/electron-vue#44]
Devtron lint check "Using latest Electron version" fails with the error in the console:

> Fetch API cannot load https://atom.io/download/atom-shell/index.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by SimulatedGREG** [comment]
@Luminess 

Is this log coming just from using the Devtron tools or are you actually making a web request?

**Comment by SimulatedGREG** [comment]
Since the Vue app sits behind the `webpack-dev-server` during development `devtron` runs into a CORS problem when accessing the most recent Electron Version. This isn't a direct problem with electron-vue itself so I will be closing this. Please know that this really isn't an issue with your app as you can also manually confirm your electron version with the latest release from [`electron`](https://github.com/electron/electron/releases). Looking at the `devtron` repo, there's already an issue made about this log, so hopefully we can get some feedback from them ([`devtron #91`](https://github.com/electron/devtron/issues/91)).
