### ISSUE TITLE
build app request header origin file://, the request be rejected

### ISSUE THREAD

**Issue by taodong0710** [SimulatedGREG/electron-vue#443]
##### Describe the issue / bug.
\# Build app request header origin file://, the request be  rejected，Http Status Code 403 and server set CORS .                 

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#
![image](https://user-images.githubusercontent.com/24261582/32216135-2330ab0e-be5f-11e7-8e78-f0cbed3804ab.png)

##### Tell me about your development environment.
  * Node version: v8.7.0
  * NPM version: 5.4.2
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by SimulatedGREG** [comment]
This is expected behavior with `electron`. In development you use a `webpack-dev-server` which uses `http://`, but in production the `file://` protocol is used. When making web requests, you need to ensure your application provides a full url path with the `http://` or `https://` protocol. This is not an issue with electron-vue.
