### ISSUE TITLE
Use renderer.js both in electron and web environments

### ISSUE THREAD

**Issue by ElectroDr3am** [SimulatedGREG/electron-vue#446]
Is it possible to use same index.html both from Electron process and browser like Chrome?

I made an app that uses it's own Hapi server to serve http requests to db and it works fine.
Now I'm trying to serve `index.html` from inside of Electron's asar but got an error 
"module is not defined" opening Hapi's route in Chrome.

As I guess `renderer.js` is compiled using **es2016** instead of **es2015**. I've tryied using webpack plugins but none of them even let me recompile an app throwing different mistakes.

Is there some good way to archive identical UI for Electron-users and Browser-users?

**Comment by SimulatedGREG** [comment]
> but got an error "module is not defined" opening Hapi's route in Chrome.

This is because the `renderer.js` is built specifically for the `electron` environment where items like `module` are actually defined. If you need a web specific build, you can run `yarn run build:web` to get something that works in Chrome. This web built is provided as a solid start for supporting web, but electron-vue has no intentions to bring further support for this output.

So, in theory, you could extend your project's build step to produce both builds and bundle in the same application.
