### ISSUE TITLE
how to add another vue package ?

### ISSUE THREAD

**Issue by m-alinasab** [SimulatedGREG/electron-vue#467]
hello .

i want add vue-awesome-swiper on electron-vue but after install ( with npm install vue-awesome-swiper --save ) and add this code on my project , Error Compile print : 

> D:\electron-apps\nex1-vue2\node_modules\vue-awesome-swiper\src\swiper.vue:1 Uncaught SyntaxError: Unexpected token <

Even the simplest package can not be installed!

Why so complex?

**Comment by FloLech** [comment]
I am facing the same issue, any solutions?

Node: v 8.9.1

**Comment by m-alinasab** [comment]
My Node js Version is 9.2.0

**Comment by mdobeck** [comment]
Are you referring to installing a Vue plug-in?  This is done the same way as a non-electric environment. See the "Using a plug-in" section. https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin

I might have misunderstood your problem so let me know.

**Comment by SimulatedGREG** [comment]
It doesn't look like `vue-awesome-swiper` should be running into this issue anymore. But to answer your original question, you would have needed to white-list this module so that vue-loader would have been able to parse the templates files it once provided.

Docs: https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html
