### ISSUE TITLE
electron.js in ES6?

### ISSUE THREAD

**Issue by simonwjackson** [SimulatedGREG/electron-vue#48]
Any way we can write the electron.js in ES6?

I'm guessing its just a matter of having babel compile it, but i'm having trouble reading the task reunners

**Comment by SimulatedGREG** [comment]
The current setup does not transpile `electron.js` with babel. There are some plans to have this working together with webpack, but the unfortunate item about that current setup is that there is no Hot Module Replacement for node processes as of yet (at least not reliable yet). But do remember, node v6 does support almost all ES6 features. The one big feature missing is using `import` / `export`, which really isn't too much of a trade off in my opinion. You could try using `babel-polyfill` or `babel-register`, but the problem here is that it would bloat your build size and you would need to manually transfer dependencies into a final build. But like I said, if you can live with using `require`, then everything else is nearly there.

**Comment by simonwjackson** [comment]
Ok, thats good to know. I can live with `require` for now. Thanks, for all the good work!

**Comment by SimulatedGREG** [comment]
No problem. 😊
