### ISSUE TITLE
can't build for windows using mac

### ISSUE THREAD

**Issue by i-am-dror** [SimulatedGREG/electron-vue#487]
npm run build:win32
npm ERR! missing script: build:win32

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/drorrash/.npm/_logs/2017-12-20T20_13_34_788Z-debug.log

**Comment by mdobeck** [comment]
Post the debug log. Like in this question:https://github.com/npm/npm/issues/8193

**Comment by innocuo** [comment]
> npm ERR! missing script: build:win32

I believe you get that error when you chose to use electron-builder instead of electron-packager 

If you're using electron-builder, on MacOS and want to build for windows, modify your package.json build script to 

`"node .electron-vue/build.js && electron-builder -w"`

Take a look at the docs for command line params for other platforms
https://www.electron.build/cli
