### ISSUE TITLE
Please use electron-prebuilt-compile

### ISSUE THREAD

**Issue by kristianmandrup** [SimulatedGREG/electron-vue#61]
Please use https://github.com/paulcbetts/electron-prebuilt-compile

It makes electron app development so much easier by compiling all the assets without any fuss!

Cheers!

**Comment by SimulatedGREG** [comment]
@kristianmandrup 

Thanks for the suggestion, but this doesn't quite make a major difference (as it may seem) since webpack is involved. Using `electron-compile` and believing it to be a full replacement for everything webpack does is not the full story. Yes they could be used in the same environment, but it doesn't quite make sense as they are both trying to solve similar problems. 

Yes they both transpile HTML/CSS/JS, but without webpack you lose major functionally in using modules, bundling code, Hot Module Replacement, minimizing & uglifying code, advanced loader configurations, and most importantly parsing Vue component files (which is a major deal breaker of course).

Don't get me wrong, `electron-compile` is great, but it doesn't mean it's the perfect solution for everything electron related. Vue really needs webpack, and webpack with `electron-compile` just doesn't make sense. So for now this won't happen.
