### ISSUE TITLE
cfonts is licensed under GPLV2

### ISSUE THREAD

**Issue by GoriGorgeSency** [SimulatedGREG/electron-vue#646]

**Comment by XanderLuciano** [comment]
IANAL, but since we are not distributing cfronts (rather it is just listed as a dependancy), and since cfonts is not related to any code you distribute (it's just a package to make the console look cool, but not needed), I'm not aware of any issues with it being GPLV2.

That said I also don't fully understand how it's license would apply to 1. a template and 2. a development tool that is unrelated to any code generated using this template. Though you didn't really specify what the actual issue is here so I'm not sure how to address this. Just let me know if I'm missing something.
