### ISSUE TITLE
`npm vue:route routeName` is broken.

### ISSUE THREAD

**Issue by radicaled** [SimulatedGREG/electron-vue#65]
##### Describe the issue / bug.
\#

It looks like `tasks/vue/route.js` is malformed after generating a project. Specifically, this chunk, on line 25 of the generated file: 
```javascript
routes.splice(
  routes.length - 2,
  0,
  routesTemplate
    .replace(//g, routeName) // <--- this isn't a valid regex expression, so the javascript parser barfs.
    .replace(/\n$/, '')
)
```

##### How can I reproduce this problem?
\#
`vue init simulatedgreg/electron-vue my-project`
`npm run vue:route foobar`

##### Tell me about your development environment.
  * Node version: 7.1.0
  * NPM version: 3.10.9
  * vue-cli version: 2.5.0
  * Operating System: Ubuntu Linux 16.04

**Comment by SimulatedGREG** [comment]
@radicaled 

I'm aware that the scripts are broken for the time being, as noted within the [docs](https://simulatedgreg.gitbooks.io/electron-vue/content/docs/vue_accessories.html). I've been meaning to rewrite them, but there hasn't been much concern about them to make it a priority since most people use snippets within their text editors.

So for now, they will still be *experimental*, unless you want to create a PR and rewrite them. Not trying to be rude, but the main concern for the time being is supporting main process bundling.

**Comment by radicaled** [comment]
Sorry, I didn't see anything in the documentation implying they were intentionally broken. When I see "experimental" I tend to think "working but rough around the edges" or "fails some edge cases," not, "doesn't work at all."

My bad.

**Comment by SimulatedGREG** [comment]
No problem, probably bad wording on my part. In the end, rewriting them is still on the todos in the [GitHub Project](https://github.com/SimulatedGREG/electron-vue/projects/2).
