### ISSUE TITLE
Help: Failed to load a static resource

### ISSUE THREAD

**Issue by komplexb** [SimulatedGREG/electron-vue#82]
##### Describe the issue / bug.
Followed the [instructions](https://simulatedgreg.gitbooks.io/electron-vue/content/docs/using_the_file_structure.html#using-static-assets) and placed CSS theme files in the static assets directory. However upon build these files can't be found. Unclear how to proceed.

Path inside semantic.css
```
  url(themes/default/assets/fonts/icons.woff2) format('woff2'), 
  url(themes/default/assets/fonts/icons.woff) format('woff'), 
  url(themes/default/assets/fonts/icons.ttf) format('truetype'), 
```

##### If visual, provide a screenshot.
![screenshot 2016-12-14 13 04 33](https://cloud.githubusercontent.com/assets/3874813/21194530/4f9766dc-c1fe-11e6-9c1c-685fb34b53f6.png)
<img width="966" alt="screenshot 2016-12-14 12 33 35" src="https://cloud.githubusercontent.com/assets/3874813/21194531/4f979c4c-c1fe-11e6-8a5f-e5d1c0c6dd51.png">
<img width="256" alt="screenshot 2016-12-14 13 10 40" src="https://cloud.githubusercontent.com/assets/3874813/21194711/e2d285b2-c1fe-11e6-86ca-f3a01151fb76.png">

##### Tell me about your development environment.
  * Node version: v6.9.1
  * NPM version: 3.10.8
  * vue-cli version: (if necessary)
  * Operating System: OSX

**Comment by SimulatedGREG** [comment]
Is there any specific reason why aren't using `npm` for semantic.css? I'm guessing maybe you are using a specific theme so that would make sense. If not, then it would be better to use from `npm` and import through webpack.

The main reason the `icons` files are missing is because anything with the `icons` in the file path will be ignored. This is initially done so `app/icons` is ignored. For a quick fix, you can edit your `config.js` and remove `icons` from the [`building.ignore`](https://github.com/SimulatedGREG/electron-vue/blob/master/template/config.js#L26) value. I'll be patching this up in a later release.

**Comment by komplexb** [comment]
Ah I see, missed that ignore bit when I was modifying that file. I ended up using inline svgs for now. But i'll make the adjustment going fwd. Thanks.
