### ISSUE TITLE
How to debug in VSCode?

### ISSUE THREAD

**Issue by erguotou520** [SimulatedGREG/electron-vue#83]
### Not issue, but question
I want to debug the main process in VSCode, and the config is bellow:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "start debug",
      "program": "${workspaceRoot}/tasks/runner.js",
      "cwd": "${workspaceRoot}"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "attach",
      "port": 5858
    }
  ]
}
```
but it can't start the electron app. I searched the issue, doc, and found no doc about how to debug.

**Comment by SimulatedGREG** [comment]
@erguotou520 

With the current setup you won't be able to debug both the renderer and main process within the VSCode debugger, but you can debug the main process. In order to get electron running you would need to set the `runtimeExecutable`. Below is a default `launch.json`modified to work with electron. Notice that the `NODE_ENV` is set to `"production"`, so make sure to run `npm run pack` to have a fresh version of your app.

```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/app/electron.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
                        // this points to the electron task runner
			"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "production"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"sourceMaps": false,
			"outDir": null,
			"localRoot": "${workspaceRoot}",
			"remoteRoot": null
		}
	]
}
```

**Comment by erguotou520** [comment]
OK, got it.

**Comment by rr326** [comment]
I've been struggling with getting this working. Perhaps you can give some pointers. 

The goal: debug the main process and the renderer process.
Ideal: hotreloading of both. (I've gotten the renderer working perfectly with your npm run dev setup.)
Good enough: Set up main to do an `npm run pack` then debug in vscode. (I found debugging main in vscode worked great and I could never get electron-inspector to work properly.)

status
I've got `npm run pack` to work (after plenty of challenges)
I've modified my launch.json to almost get this working. But now I'm running into  dealing with an Uglified, webpacked code base to start debugging my errors. 

I think the immediate problem is how to tie all the sourcmaps together so that when vscode shows a bug, I see my original software, and not something like this:
```
{return t&&t.__esModule?t:{default:t}}function o(t,n){var e=a.createServer();e.listen({port:t,host:"localhost",exclusive:!0},function(r){e.once("close",function(){
return u.info("getPort SUCCESS - ",t),n(t),t}),e.close()}),e.on("error",function(e){o(t+1,n)})
```

launch.json
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/app/dist/main.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}/app/dist",
            // this points to the electron task runner
			"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
			"runtimeArgs": [
                "--nolazy"
			],
			"env": {
				"NODE_ENV": "production"
			},
			"console": "internalConsole",
			"sourceMaps": false,
			"outFiles": []

		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"sourceMaps": false,
			"outFiles": [],
			"localRoot": "${workspaceRoot}",
			"remoteRoot": null
		}
	]
}
```

webpack.main.config.js
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/app/dist/main.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}/app/dist",
            // this points to the electron task runner
			"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
			"runtimeArgs": [
                "--nolazy"
			],
			"env": {
				"NODE_ENV": "production"
			},
			"console": "internalConsole",
			"sourceMaps": false,
			"outFiles": []

		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"sourceMaps": false,
			"outFiles": [],
			"localRoot": "${workspaceRoot}",
			"remoteRoot": null
		}
	]
}
```

Thanks for any help. Even with your awesome headstart I've found the hardest part of this project to be getting all the tooling to work. It would have been impossible without electron-vue.
