### ISSUE TITLE
Can't package .node file & use child_process.fork

### ISSUE THREAD

**Issue by llwslc** [SimulatedGREG/electron-vue#86]
node_loader use absolute path, package can't find in other pc. example: npm serialport modules.
webpack build all js to build.js, child_process.fork can't find path.

how to improve?

Thank you very much.

**Comment by SimulatedGREG** [comment]
Using `node-loader` really isn't the easiest thing to accomplish.

`__dirname` within webpack doesn't work as you would expect when in a regular node.js application. In order to get a better file reference you could add `const __root = __dirname` within your `index.ejs` file that way your JS has a global variable to reference to when using absolute paths that could be combined with the use of `path`.

This probably doesn't solve your issue completely but should give a general idea on what is happening. Since this isn't a direct issue with electron-vue, I will be closing this. Also the use of native node modules should be easier in the near future as there are major plans for supporting these types of situations.
