### ISSUE TITLE
Separate ui code (renderer process) from main process

### ISSUE THREAD

**Issue by brpaz** [SimulatedGREG/electron-vue#91]
Hello.
First of all, congratulations for this project. Looks really good.

For more complex  Apps, having a single electron.js file seems not a good idea. A common approach is to have separate folders like (renderer and main) where each part of the application goes. Whats your vision about this? 

Also the issue that main electron modules are not bundled in the build process is a blocker for me. Its an Electron app, after all.  Not just a client side vue app. I think it will be very rate cases where you dont need to include any kind of external node modules into your main process code. 

Thank you.

**Comment by SimulatedGREG** [comment]
@brpaz 

Sorry for the late reply, been on away for the holidays.

Main process support has been underway and this will be taken into consideration. Big changes like this have been put on hold until wepback 2 has been officially released. I'm hoping that happens soon, because the wait is getting ridiculous in my opinion. If you need modules at this very moment, you can simply update the ignore filter within the `config.js` build setting so they exist in production. Also, going to close this as it is more of a discussion.
