### ISSUE TITLE
How can I build the app as an installable or executable file ?

### ISSUE THREAD

**Issue by koolay** [SimulatedGREG/electron-vue#94]
It's a great starter for making an app of cross platform. 

I has a problem that  running the command `npm run build`  deployed into a folder with many files. Is it possible to build the app as an installable or executable file ?

**Comment by SimulatedGREG** [comment]
@koolay 

The current setup uses `electron-packager` for making production builds. If you need to create full installers then you'll need to use `electron-builder`. It can be a little complicated at first to setup because there are many configurations available, but it is easy to use with the current project structure. Support for `electron-builder` will come in the near future.

**Comment by koolay** [comment]
@SimulatedGREG 
Thanks for your reply.
